### ISSUE TITLE
In staging, preview page not available if path contains letters or hyphens

### ISSUE THREAD

**Issue by Schuamy** [CDIEurope/www.appsforgood.org#15]
- When I enter a path with numbers (/Awards2019) and click preview I get page not found error
- When I enter a path with hyphen (/Awards-new) and click preview I get page not found error
- When I enter a path with letters only (/Awardsnew) and click preview I go to a working preview page on the staging environment

This happens if I create a new page and enter a new path. It also happens if I try to change an existing path on an existing page.

<img width="1243" alt="Screen Shot 2019-03-22 at 09 29 03" src="https://user-images.githubusercontent.com/17194929/54813690-0681a880-4c86-11e9-99e2-7a124468ae97.png">
<img width="1244" alt="Screen Shot 2019-03-22 at 09 29 11" src="https://user-images.githubusercontent.com/17194929/54813709-0bdef300-4c86-11e9-8372-fb47ef326148.png">
<img width="1244" alt="Screen Shot 2019-03-22 at 09 29 37" src="https://user-images.githubusercontent.com/17194929/54813723-139e9780-4c86-11e9-884b-de3a023cc14a.png">
<img width="1249" alt="Screen Shot 2019-03-22 at 09 29 55" src="https://user-images.githubusercontent.com/17194929/54813729-17cab500-4c86-11e9-83b0-99e879480154.png">
<img width="1254" alt="Screen Shot 2019-03-22 at 09 34 24" src="https://user-images.githubusercontent.com/17194929/54813734-1c8f6900-4c86-11e9-98f7-89a0be759dd7.png">
<img width="1240" alt="Screen Shot 2019-03-22 at 09 34 31" src="https://user-images.githubusercontent.com/17194929/54813744-21ecb380-4c86-11e9-9fee-93064bae9aa0.png">

**Comment by moomerman** [comment]
@Schuamy morning! I've just pushed a fix to allow numbers in the path, should be fine now.  Dashes are allowed but capital letters aren't so I think that is why the `Awards-new` one failed.
