### ISSUE TITLE
Partner logos 40-50% bigger

### ISSUE THREAD

**Issue by noamso** [CDIEurope/www.appsforgood.org#4]
See bottom of homepage:
https://www.appsforgood.org/

**Comment by moomerman** [comment]
@noamso 

Should this also apply to the partner logos on the partners page?

https://www.appsforgood.org/partners

![image](https://user-images.githubusercontent.com/23323/51441341-48af5d80-1cc8-11e9-8a2c-d10ea5763a44.png)
