### ISSUE TITLE
Tweaks to course session list

### ISSUE THREAD

**Issue by Schuamy** [CDIEurope/www.appsforgood.org#57]
The session links at the top of the course page feel crowded now that I've put the titles in, as some of the titles are quite long. Could we give them more space?

Tried mocking up in the browser below...

<img width="1179" alt="Screen Shot 2019-05-28 at 15 18 54" src="https://user-images.githubusercontent.com/17194929/58486134-35703b00-815d-11e9-9eb5-a0cf4c56b42f.png">
<img width="1005" alt="Screen Shot 2019-05-28 at 15 20 05" src="https://user-images.githubusercontent.com/17194929/58486140-3739fe80-815d-11e9-8ebf-45e40ebee9db.png">

**Comment by noamso** [comment]
To add to this, I'm not sure font-lato is being used to style this text and the text size is too big. Ideally would be the same size as body copy above but a slightly heavier weight.

**Comment by abpaul** [comment]
Closed by #58
