### ISSUE TITLE
Form backgrounds could do with an outline + rounding

### ISSUE THREAD

**Issue by noamso** [CDIEurope/www.appsforgood.org#60]
Login, Sign up and Password reminder forms could do with a 1px grey ("border rounded border-grey") rounded border to make consistent with other elements and help make forms stand out better.

![login+border+rounded+border-grey](https://user-images.githubusercontent.com/4624814/58629690-0ed51000-82d5-11e9-8a96-1a9672fe115f.png)
![signup-border+rounded+border-grey](https://user-images.githubusercontent.com/4624814/58629691-0f6da680-82d5-11e9-9371-85163d608c8f.png)

**Comment by abpaul** [comment]
Closed by #58
