### ISSUE TITLE
Slides embed needs to be full height and width

### ISSUE THREAD

**Issue by noamso** [CDIEurope/www.appsforgood.org#61]
For example on [Machine Learning course page](https://afg-staging-pr-22.herokuapp.com/machine-learning-beta) the embed should look like we have on [course overview page](https://www.appsforgood.org/courses/app-standard). 

![Screen Shot 2019-05-30 at 12 19 05](https://user-images.githubusercontent.com/4624814/58629847-7ab77880-82d5-11e9-9d33-ec1add0ea859.png)

**Comment by abpaul** [comment]
Closed by #58
