### ISSUE TITLE
Reset password not working

### ISSUE THREAD

**Issue by noamso** [CDIEurope/www.appsforgood.org#62]
Trying to [reset password](https://afg-staging-pr-22.herokuapp.com/passwords/new) returns an error.

![Screen Shot 2019-05-30 at 12 36 44](https://user-images.githubusercontent.com/4624814/58630559-b6ebd880-82d7-11e9-978a-15c7af8e81f1.png)

**Comment by abpaul** [comment]
Closed by #58
