### ISSUE TITLE
Implement "Reset your password" and send email

### ISSUE THREAD

**Issue by noamso** [CDIEurope/www.appsforgood.org#63]
If not, we can create a Googe Doc of content.

cc @Schuamy

**Comment by Schuamy** [comment]
I will write the copy. Do we need copy for anything besides:

Account confirmation
Account confirmed
Password reminder

**Comment by Schuamy** [comment]
Decision was taken to hold off on account confirmation emails for June testing.

Copy for password reset email below..



Hi Amy,

You told us you'd like to reset your password. You can click the link below to choose a new password:

If you didn't mean to reset your password, just ignore this email. Your password will not change.

Best wishes,

The Apps for Good Team

**Comment by noamso** [comment]
Looks like this is working but message needs to be friendlier than the one received.

![email](https://user-images.githubusercontent.com/4624814/59913785-c78ffa00-9410-11e9-81b0-37c38602f2c8.png)

**Comment by abpaul** [comment]
@noamso I'm preparing a copy update - what subject line should we use?

**Comment by abpaul** [comment]
@noamso we decided to go with `Reset password for your Apps for Good Account` - let me know if you want a different subject line though :)
