### ISSUE TITLE
Educator needs to be able to remove the welcome message

### ISSUE THREAD

**Issue by noamso** [CDIEurope/www.appsforgood.org#64]
Welcome message is useful for first-time use but then just a nuisance and gets in the way.

Can we add a X top right so teacher can remove or have it auto disappear after first visit?

![Screen Shot 2019-05-30 at 13 43 24](https://user-images.githubusercontent.com/4624814/58633715-2e723580-82e1-11e9-8b7e-38dd671e16b8.png)

**Comment by abpaul** [comment]
Closed by #58
