### ISSUE TITLE
On course page in staging the 'view course' button should take users to the new course page

### ISSUE THREAD

**Issue by Schuamy** [CDIEurope/www.appsforgood.org#74]
Right the ‘view the course’ buttons on the course cards on [https://afg-staging-pr-22.herokuapp.com/courses](https://afg-staging-pr-22.herokuapp.com/courses) link to the old course pages.

These links are auto-generated from the content model. They cannot be changed manually.

Will we link these course cards to the new test course pages on the staging site - so when they visit [https://afg-staging-pr-22.herokuapp.com/courses](https://afg-staging-pr-22.herokuapp.com/courses) and click 'view the course' they see either the logged out or logged in version of the new course page?

**Comment by alexthomas** [comment]
@Schuamy the 'view the course' button will now take you to a signed out/signed in version of the page. To do this you simply need to

1) create a signed in course page in contentful
2) add this page path to the signed_in_path to the course model

I have done this for you for App in a day to show you how to do it. But don't forget you'll still need to add the sessions and core resources for the pages to display properly. Also the signed out page will look a little odd on staging as it will display all the new stuff but also the old stuff as you still need that for production

https://app.contentful.com/spaces/g6umu3wl1djc/entries/6qohiRXbSxPX7kSWv57gie
https://app.contentful.com/spaces/g6umu3wl1djc/entries/1aAedh35fCCUyy60Sikeyw
