### ISSUE TITLE
Do we need signed in path for courses?

### ISSUE THREAD

**Issue by noamso** [CDIEurope/www.appsforgood.org#80]
When a user is logged in and goes to https://afg-staging-pr-22.herokuapp.com/courses/machine-learning-beta the page renders/works as expected for logged in user.

Why do we need a logged in path? i.e. https://afg-staging-pr-22.herokuapp.com/courses/machine-learning-beta-signed-in

We really need one course URL for logged out and logged in users.

Related issues:
1. This logged in URL gets linked to from courses page when logged in, therefore would need to change
2. Course link on account page links to logged in course URL so that would need to change too
3. On course page, would need to show "Please *Login* or *sign up* to access all of the course content"

cc @Schuamy @abpaul

**Comment by abpaul** [comment]
Resolved by #82
