### ISSUE TITLE
Typo in course bookmarks drop-down menu

### ISSUE THREAD

**Issue by Schuamy** [CDIEurope/www.appsforgood.org#93]
Says "App Development Extend"

Should be "App Development Extended" please

<img width="937" alt="Screen Shot 2019-07-01 at 10 25 46" src="https://user-images.githubusercontent.com/17194929/60425635-dafa4c80-9bea-11e9-92e5-0e4cf39c5492.png">

**Comment by abpaul** [comment]
:wave: hi @Schuamy - we've fixed the typo!
